import React from "react";
import "@fontsource/inter/latin-400.css";
import "@fontsource/inter/latin-500.css";
import "@fontsource/inter/latin-600.css";
import "@fontsource/inter/latin-700.css";
import "@fontsource/ibm-plex-mono/latin-400.css";
import "@fontsource/ibm-plex-mono/latin-500.css";
import { createRoot } from "react-dom/client";
import App from "./pages/App.jsx";
import "./styles/app.css";
createRoot(document.getElementById("root")).render(<App />);
